using Godot;

namespace Bulwark.Dev;

/// <summary>
/// Renders the PSX modular asset library (scenes/dev/psx_library_spike.tscn).
///
/// The scene is generated by G:/crocotile-mcp/examples/build_psx_library.py and holds three
/// things side by side, all under one sun so nothing can be judged against a different light:
///   Rows      — every object in the kit, laid out in labelled rows on a grass pad.
///   Assembly  — a wall run built the way the outpost will build it: mixed straight variants,
///               a corner, both towers, and the gate set across its 6 m opening.
///   Terrain   — outpost_terrain_psx.glb parked 200 m along +X, terrain only.
///
/// Captures (1280x720 each, to the scratchpad):
///   psxlib_rows.png / psxlib_rowsclose.png / psxlib_wall.png / psxlib_wallclose.png
///   psxlib_terrain.png
///
/// Camera rigs are Marker3D pairs authored in the scene and the LookAt happens here, so no
/// hand-written rotation basis can silently transpose (a Transform3D literal in a .tscn is
/// row-major while the constructor takes column vectors).
///
/// Must run rendered (not --headless):
///   Godot_v4.6.2-stable_mono_win64.exe --path bulwark res://scenes/dev/psx_library_spike.tscn
/// </summary>
public partial class PsxLibraryShotSpike : Node3D
{
    private const string OutDir =
        @"C:\Users\Midge\AppData\Local\Temp\claude\G--Godot-Gamestorming\2bd27b51-0eee-4938-8f02-f94cf931795f\scratchpad";

    private const double SettleSeconds = 0.35;

    private readonly (string Name, float Fov)[] _shots =
    {
        ("Rows", 42f),
        ("RowsClose", 45f),
        ("Towers", 42f),
        ("Wall", 55f),
        ("WallClose", 48f),
        ("Terrain", 26f),
    };

    private Camera3D? _camera;
    private int _shot = -1;
    private double _timer;

    public override void _Ready()
    {
        _camera = new Camera3D { Name = "ShotCamera", Current = true, Far = 900f };
        AddChild(_camera);
        GD.Print($"[psxlib] ready, {_shots.Length} captures queued");
    }

    public override void _Process(double delta)
    {
        _timer += delta;
        if (_timer < (_shot < 0 ? 1.0 : SettleSeconds))
            return;

        if (_shot >= 0)
            Capture();

        _shot++;
        _timer = 0;

        if (_shot >= _shots.Length)
        {
            GD.Print("[psxlib] done, quitting");
            GetTree().Quit(0);
            return;
        }

        Aim();
    }

    private void Aim()
    {
        (string name, float fov) = _shots[_shot];
        var pos = GetNode<Marker3D>($"%Cam{name}Pos");
        var target = GetNode<Marker3D>($"%Cam{name}Target");
        _camera!.Fov = fov;
        _camera.GlobalPosition = pos.GlobalPosition;
        _camera.LookAt(target.GlobalPosition, Vector3.Up);
    }

    private void Capture()
    {
        string file = $"psxlib_{_shots[_shot].Name.ToLowerInvariant()}.png";
        Image img = GetViewport().GetTexture().GetImage();
        // hdr_2d viewports hand back linear-space data; convert or the PNG comes out crushed.
        img.Convert(Image.Format.Rgba8);
        img.LinearToSrgb();
        img.Resize(1280, 720, Image.Interpolation.Bilinear);
        img.SavePng($"{OutDir}\\{file}");
        GD.Print($"[psxlib] saved {file}");
    }
}
